name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: |
          cd ./books
          a='up --detach'
          echo "$a"
          docker-compose "$a"
      - name: Test
        run: |
          ls -la
          cd ./code
          ls -la
          cd ../books
          ls -la
          a='exec web python manage.py test'
          docker-compose "$a"
#         run: docker-compose exec -d web python manage.py test -v 4

