name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack and test
        run: cd books && docker-compose up -d  && docker-compose exec web python manage.py test -v 4
     

